#!/bin/bash
set -euxo pipefail

echo "$INSTRUQT_USER_NAME running challenge check script on $INSTRUQT_CHALLENGE_ID"


# if ! grep "dashboard" /o11y/index.ts; then
#     fail-message "Couldn't find the dashboard output. Did you use dashboards?"
#     exit 1
# fi