#!/bin/bash
set -euxo pipefail

# Check if the tags exists on the apps

if ! grep "team" /o11y/index.ts; then
    fail-message "Couldn't find the team tag. Did you use tags?"
    exit 1
fi

if ! grep "env" /o11y/index.ts; then
    fail-message "Couldn't find the team tag. Did you use tags?"
    exit 1
fi