#!/bin/bash
set -euxo pipefail

echo "$INSTRUQT_USER_NAME running challenge check script on $INSTRUQT_CHALLENGE_ID"


# if ! grep "workload" /o11y/index.ts; then
#     fail-message "Couldn't find the workload output. Did you use workloads?"
#     exit 1
# fi