#!/bin/bash
set -euxo pipefail

echo "$INSTRUQT_USER_NAME running challenge check script on $INSTRUQT_CHALLENGE_ID"


# if ! grep "synthetic" /o11y/index.ts; then
#     fail-message "Couldn't find synthetic monitors. Did you use synthetic monitors?"
#     exit 1
# fi