#!/bin/bash
set -euxo pipefail

echo "$INSTRUQT_USER_NAME running challenge check script on $INSTRUQT_CHALLENGE_ID"


# if ! grep "alerts" /o11y/index.ts; then
#     fail-message "Couldn't find alerts. Did you use alerts?"
#     exit 1
# fi